import GenericBase from './genericbase'
import PrusaSlicer from './prusaslicer'
import Cura from './cura'
import SuperSlicer from './superslicer'
import OrcaSlicer from './orcaslicer'
import ideaMaker from './ideamaker'
import KiriMoto from './kirimoto'

export function slicerFactory(gcode) {
   if (gcode == null) return null

   let header = gcode.substring(0, 10000)
   if (header.includes('; generated by PrusaSlicer')) {
      return new PrusaSlicer()
   } else if (header.includes(';Generated with Cura_SteamEngine')) {
      return new Cura()
   } else if (header.includes('; generated by SuperSlicer')) {
      return new SuperSlicer()
   } else if (header.includes('Sliced by ideaMaker')) {
      return new ideaMaker()
   } else if (header.includes('; Generated by Kiri:Moto')) {
      return new KiriMoto()
   } else if (header.includes('generated by OrcaSlicer ')) {
      return new OrcaSlicer()
   }

   return new GenericBase()
}
